# Generated by Django 5.0.7 on 2024-09-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_image', models.ImageField(upload_to='image/')),
                ('c_name', models.CharField(max_length=25)),
                ('c_desc', models.CharField(max_length=400)),
                ('c_price', models.IntegerField()),
                ('c_author', models.CharField(max_length=50)),
            ],
        ),
    ]
