# Generated by Django 5.0.7 on 2024-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_name',
            field=models.CharField(max_length=250),
        ),
    ]
